(() => {
 const canvas=document.getElementById('invitationCanvas'),intro=document.getElementById('invitationIntro');if(!canvas||!intro)return;
 const ctx=canvas.getContext('2d',{alpha:true});let dpr=1,w=0,h=0,raf=0,start=0,active=false,particles=[];
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=t=>1-Math.pow(1-clamp(t),3);
 function resize(){dpr=Math.min(devicePixelRatio||1,innerWidth<760?1.5:2);w=innerWidth;h=innerHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
 function seed(){particles=[];for(let i=0,n=innerWidth<760?26:42;i<n;i++)particles.push({kind:i%7===0?'petal':'dust',x:.12+Math.random()*.76,y:.18+Math.random()*.7,r:Math.random()*1.8+.5,vx:(Math.random()-.5)*.00005,vy:Math.random()*.000055+.000025,rot:Math.random()*6.28,spin:(Math.random()-.5)*.0012,phase:Math.random()*6.28,alpha:.25+Math.random()*.55})}
 function backdrop(t){const g=ctx.createRadialGradient(w*.5,h*.43,20,w*.5,h*.48,Math.max(w,h)*.72);g.addColorStop(0,'rgba(102,20,31,'+(0.11+ease(t)*.05)+')');g.addColorStop(.5,'rgba(48,8,16,.05)');g.addColorStop(1,'rgba(20,5,8,.16)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
 function glow(t){const p=ease((t-1100)/2100);if(p<=0)return;const x=w*.5,y=h*(innerWidth<760?.49:.5),r=Math.min(w,h)*(.16+.05*p),g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(244,194,103,'+(.13*p)+')');g.addColorStop(.45,'rgba(205,128,54,'+(.055*p)+')');g.addColorStop(1,'rgba(130,60,30,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
 function particle(p,t){const reveal=ease((t-(p.kind==='petal'?1750:900))/1000);if(reveal<=0)return;p.x+=p.vx*16.7;p.y+=p.vy*16.7;p.rot+=p.spin*16.7;if(p.y>1.08){p.y=-.05;p.x=.1+Math.random()*.8}const x=p.x*w+Math.sin(t*.0007+p.phase)*(p.kind==='petal'?10:3),y=p.y*h;ctx.save();ctx.translate(x,y);ctx.rotate(p.rot);if(p.kind==='petal'){ctx.globalAlpha=p.alpha*reveal*.72;const g=ctx.createLinearGradient(-7,-4,8,5);g.addColorStop(0,'#7c1d2b');g.addColorStop(1,'#b84a54');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-9,0);ctx.bezierCurveTo(-3,-7,8,-6,10,0);ctx.bezierCurveTo(4,8,-5,7,-9,0);ctx.fill()}else{ctx.globalAlpha=p.alpha*reveal*(.55+.35*Math.sin(t*.003+p.phase));ctx.fillStyle='#e7bc69';ctx.shadowColor='rgba(239,190,91,.65)';ctx.shadowBlur=6;ctx.beginPath();ctx.arc(0,0,p.r,0,6.283);ctx.fill()}ctx.restore()}
 function burst(t){const q=clamp((t-650)/1350);if(q<=0||q>=1)return;const cx=w*.5,cy=h*(innerWidth<760?.56:.57);for(let i=0;i<18;i++){const a=i*2.399,d=ease(q)*(35+(i%6)*9);ctx.globalAlpha=(1-q)*.48;ctx.fillStyle='#efc76f';ctx.beginPath();ctx.arc(cx+Math.cos(a)*d,cy+Math.sin(a)*d*.55,1+(i%3)*.35,0,6.283);ctx.fill()}ctx.globalAlpha=1}
 function frame(now){if(!active)return;const t=now-start;ctx.clearRect(0,0,w,h);backdrop(t);glow(t);burst(t);particles.forEach(p=>particle(p,t));if(t<6100)raf=requestAnimationFrame(frame);else stop()}
 function play(){if(reduce||active)return;active=true;start=performance.now();seed();raf=requestAnimationFrame(frame)}
 function stop(){active=false;cancelAnimationFrame(raf);ctx.clearRect(0,0,w,h)}
 resize();addEventListener('resize',resize,{passive:true});window.WeddingInvitationCanvas={play,stop};
})();