create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  guest_name text not null
    check (
      char_length(trim(guest_name)) >= 1
      and char_length(trim(guest_name)) <= 120
    ),
  attendance text not null
    check (attendance in ('yes', 'no', 'maybe')),
  guest_count integer not null default 1
    check (guest_count between 0 and 10),
  message text
    check (message is null or char_length(message) <= 1000),
  event_code text not null default 'general'
    check (char_length(event_code) <= 50),
  created_at timestamptz not null default now(),
  phone text
    check (phone is null or char_length(phone) <= 40),
  event_choice text not null default 'both'
    check (event_choice in ('bride', 'groom', 'both'))
);

alter table public.rsvp enable row level security;

-- Frontend RSVP is intentionally write-only:
-- guests may submit, but cannot read or modify the guest list.
revoke all on table public.rsvp from anon, authenticated;
grant insert on table public.rsvp to anon, authenticated;
grant usage, select on sequence public.rsvp_id_seq to anon, authenticated;

drop policy if exists public_can_submit_rsvp on public.rsvp;

create policy public_can_submit_rsvp
on public.rsvp
for insert
to anon, authenticated
with check (
  char_length(trim(guest_name)) between 1 and 120
  and attendance in ('yes', 'no', 'maybe')
  and guest_count between 0 and 10
  and (phone is null or char_length(phone) <= 40)
  and event_choice in ('bride', 'groom', 'both')
  and (message is null or char_length(message) <= 1000)
);


-- =========================================================
-- Wedding Gallery CMS (free-tier friendly)
-- =========================================================
create table if not exists public.gallery_albums (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  description text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery_images (
  id uuid primary key default gen_random_uuid(),
  album_id uuid not null references public.gallery_albums(id) on delete cascade,
  original_path text not null,
  image_path text not null,
  title text,
  caption text,
  alt_text text,
  title_en text,
  title_ja text,
  caption_en text,
  caption_ja text,
  alt_text_en text,
  alt_text_ja text,
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  sort_order integer not null default 0,
  is_cover boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists gallery_images_album_sort_idx
  on public.gallery_images(album_id, sort_order, created_at);

create unique index if not exists gallery_one_cover_per_album_idx
  on public.gallery_images(album_id)
  where is_cover = true;

alter table public.gallery_albums enable row level security;
alter table public.gallery_images enable row level security;

revoke all on table public.gallery_albums from anon, authenticated;
revoke all on table public.gallery_images from anon, authenticated;

grant select on table public.gallery_albums to anon, authenticated;
grant select on table public.gallery_images to anon, authenticated;
grant insert, update, delete on table public.gallery_albums to authenticated;
grant insert, update, delete on table public.gallery_images to authenticated;

drop policy if exists gallery_albums_public_read on public.gallery_albums;
create policy gallery_albums_public_read on public.gallery_albums
for select to anon
using (is_published = true);

drop policy if exists gallery_albums_admin_read on public.gallery_albums;
create policy gallery_albums_admin_read on public.gallery_albums
for select to authenticated
using (
  is_published = true
  or ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
);

drop policy if exists gallery_albums_admin_insert on public.gallery_albums;
create policy gallery_albums_admin_insert on public.gallery_albums
for insert to authenticated
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists gallery_albums_admin_update on public.gallery_albums;
create policy gallery_albums_admin_update on public.gallery_albums
for update to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com')
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists gallery_albums_admin_delete on public.gallery_albums;
create policy gallery_albums_admin_delete on public.gallery_albums
for delete to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists gallery_images_public_read on public.gallery_images;
create policy gallery_images_public_read on public.gallery_images
for select to anon
using (
  is_published = true
  and exists (
    select 1 from public.gallery_albums a
    where a.id = album_id and a.is_published = true
  )
);

drop policy if exists gallery_images_admin_read on public.gallery_images;
create policy gallery_images_admin_read on public.gallery_images
for select to authenticated
using (
  (
    is_published = true
    and exists (
      select 1 from public.gallery_albums a
      where a.id = album_id and a.is_published = true
    )
  )
  or ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
);

drop policy if exists gallery_images_admin_insert on public.gallery_images;
create policy gallery_images_admin_insert on public.gallery_images
for insert to authenticated
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists gallery_images_admin_update on public.gallery_images;
create policy gallery_images_admin_update on public.gallery_images
for update to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com')
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists gallery_images_admin_delete on public.gallery_images;
create policy gallery_images_admin_delete on public.gallery_images
for delete to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('wedding-originals', 'wedding-originals', false, 20971520, array['image/jpeg','image/png','image/webp','image/heic']),
  ('wedding-gallery', 'wedding-gallery', true, 6291456, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists wedding_media_admin_select on storage.objects;
create policy wedding_media_admin_select on storage.objects
for select to authenticated
using (
  bucket_id in ('wedding-originals','wedding-gallery')
  and ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
);

drop policy if exists wedding_media_admin_insert on storage.objects;
create policy wedding_media_admin_insert on storage.objects
for insert to authenticated
with check (
  bucket_id in ('wedding-originals','wedding-gallery')
  and ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
);

drop policy if exists wedding_media_admin_update on storage.objects;
create policy wedding_media_admin_update on storage.objects
for update to authenticated
using (
  bucket_id in ('wedding-originals','wedding-gallery')
  and ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
)
with check (
  bucket_id in ('wedding-originals','wedding-gallery')
  and ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
);

drop policy if exists wedding_media_admin_delete on storage.objects;
create policy wedding_media_admin_delete on storage.objects
for delete to authenticated
using (
  bucket_id in ('wedding-originals','wedding-gallery')
  and ((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com'
);

insert into public.gallery_albums (title, slug, description, sort_order)
values
  ('Pre-Wedding', 'pre-wedding', 'Khoảnh khắc trước ngày cưới của Hải & Mỹ', 10),
  ('Nhà gái', 'nha-gai', 'Lễ Vu Quy và tiệc cưới nhà gái', 20),
  ('Nhà trai', 'nha-trai', 'Lễ Thành Hôn và tiệc cưới nhà trai', 30)
on conflict (slug) do nothing;

-- Admin may read RSVP, guests remain write-only.
grant select on table public.rsvp to authenticated;

drop policy if exists admin_can_read_rsvp on public.rsvp;
create policy admin_can_read_rsvp on public.rsvp
for select to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');


-- Multilingual gallery metadata
alter table public.gallery_images
  add column if not exists title_en text,
  add column if not exists title_ja text,
  add column if not exists caption_en text,
  add column if not exists caption_ja text,
  add column if not exists alt_text_en text,
  add column if not exists alt_text_ja text;


-- Homepage / editorial gallery controls
alter table public.gallery_images
  add column if not exists show_on_homepage boolean not null default true,
  add column if not exists display_size text not null default 'auto',
  add column if not exists is_featured boolean not null default false,
  add column if not exists is_hero boolean not null default false;

alter table public.gallery_images
  drop constraint if exists gallery_images_display_size_check;

alter table public.gallery_images
  add constraint gallery_images_display_size_check
  check (display_size in ('auto','small','tall','wide','large'));

create unique index if not exists gallery_one_hero_idx
  on public.gallery_images ((is_hero))
  where is_hero = true;


-- Display focus point shared by desktop/mobile crops
alter table public.gallery_images
  add column if not exists focus_x numeric(5,2) not null default 50,
  add column if not exists focus_y numeric(5,2) not null default 50;

alter table public.gallery_images
  drop constraint if exists gallery_images_focus_x_check,
  drop constraint if exists gallery_images_focus_y_check;

alter table public.gallery_images
  add constraint gallery_images_focus_x_check check (focus_x between 0 and 100),
  add constraint gallery_images_focus_y_check check (focus_y between 0 and 100);


-- Hero display settings
alter table public.gallery_images
  add column if not exists hero_layout text not null default 'full',
  add column if not exists hero_desktop_ratio text not null default '16:9',
  add column if not exists hero_mobile_ratio text not null default '4:5',
  add column if not exists hero_zoom numeric(4,2) not null default 1.00;

alter table public.gallery_images
  drop constraint if exists gallery_images_hero_layout_check,
  drop constraint if exists gallery_images_hero_desktop_ratio_check,
  drop constraint if exists gallery_images_hero_mobile_ratio_check,
  drop constraint if exists gallery_images_hero_zoom_check;

alter table public.gallery_images
  add constraint gallery_images_hero_layout_check
    check (hero_layout in ('full','framed','split','minimal')),
  add constraint gallery_images_hero_desktop_ratio_check
    check (hero_desktop_ratio in ('auto','16:9','3:2','4:3','4:5')),
  add constraint gallery_images_hero_mobile_ratio_check
    check (hero_mobile_ratio in ('auto','4:5','3:4','1:1')),
  add constraint gallery_images_hero_zoom_check
    check (hero_zoom between 1 and 1.6);


-- Hero spacing control
alter table public.gallery_images
  add column if not exists hero_spacing text not null default 'normal';

alter table public.gallery_images
  drop constraint if exists gallery_images_hero_spacing_check;

alter table public.gallery_images
  add constraint gallery_images_hero_spacing_check
    check (hero_spacing in ('compact','normal','spacious'));


-- Global website presentation settings
create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  animation_mode text not null default 'elegant',
  updated_at timestamptz not null default now()
);

alter table public.site_settings
  drop constraint if exists site_settings_animation_mode_check;

alter table public.site_settings
  add constraint site_settings_animation_mode_check
  check (animation_mode in ('minimal','elegant','wow'));

insert into public.site_settings (id, animation_mode)
values (1, 'elegant')
on conflict (id) do nothing;

alter table public.site_settings enable row level security;
revoke all on table public.site_settings from anon, authenticated;
grant select on table public.site_settings to anon, authenticated;
grant update on table public.site_settings to authenticated;

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings
for select to anon, authenticated using (true);

drop policy if exists site_settings_admin_update on public.site_settings;
create policy site_settings_admin_update on public.site_settings
for update to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com')
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');


-- =========================================================
-- Wedding CMS + personalized guest invitations
-- =========================================================
create table if not exists public.site_content (
  key text primary key check (key ~ '^[a-z0-9._-]+$'),
  value_vi text,
  value_en text,
  value_ja text,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;
revoke all on table public.site_content from anon, authenticated;
grant select on table public.site_content to anon, authenticated;
grant insert, update, delete on table public.site_content to authenticated;

drop policy if exists site_content_public_read on public.site_content;
create policy site_content_public_read on public.site_content
for select to anon, authenticated using (true);

drop policy if exists site_content_admin_insert on public.site_content;
create policy site_content_admin_insert on public.site_content
for insert to authenticated
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists site_content_admin_update on public.site_content;
create policy site_content_admin_update on public.site_content
for update to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com')
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

drop policy if exists site_content_admin_delete on public.site_content;
create policy site_content_admin_delete on public.site_content
for delete to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

create table if not exists public.guest_invites (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  guest_name text not null check (char_length(trim(guest_name)) between 1 and 120),
  phone text check (phone is null or char_length(phone) <= 40),
  event_choice text not null default 'both' check (event_choice in ('bride','groom','both')),
  max_guests integer not null default 1 check (max_guests between 1 and 10),
  internal_note text check (internal_note is null or char_length(internal_note) <= 1000),
  is_active boolean not null default true,
  import_source text not null default 'manual' check (import_source in ('manual','csv')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.guest_invites
  add column if not exists import_source text not null default 'manual';

alter table public.guest_invites
  drop constraint if exists guest_invites_import_source_check;

alter table public.guest_invites
  add constraint guest_invites_import_source_check
  check (import_source in ('manual','csv'));

create index if not exists guest_invites_event_active_idx
  on public.guest_invites(event_choice, is_active);

create index if not exists guest_invites_phone_idx
  on public.guest_invites(phone)
  where phone is not null;

alter table public.guest_invites enable row level security;
revoke all on table public.guest_invites from anon, authenticated;
grant select, insert, update, delete on table public.guest_invites to authenticated;

drop policy if exists guest_invites_admin_all on public.guest_invites;
create policy guest_invites_admin_all on public.guest_invites
for all to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com')
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

alter table public.rsvp
  add column if not exists invite_id uuid references public.guest_invites(id) on delete set null,
  add column if not exists internal_note text,
  add column if not exists contacted_at timestamptz;

create index if not exists rsvp_invite_id_idx on public.rsvp(invite_id);

grant update on table public.rsvp to authenticated;

drop policy if exists admin_can_update_rsvp on public.rsvp;
create policy admin_can_update_rsvp on public.rsvp
for update to authenticated
using (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com')
with check (((select auth.jwt())->>'email') = 'phamvuhai23@gmail.com');

create or replace function public.get_wedding_invite(p_token text)
returns table (
  id uuid,
  guest_name text,
  phone text,
  event_choice text,
  max_guests integer
)
language sql
security definer
set search_path = public
stable
as $$
  select gi.id, gi.guest_name, gi.phone, gi.event_choice, gi.max_guests
  from public.guest_invites gi
  where gi.token::text = p_token
    and gi.is_active = true
  limit 1;
$$;

revoke all on function public.get_wedding_invite(text) from public;
grant execute on function public.get_wedding_invite(text) to anon;

insert into public.site_content(key,value_vi,value_en,value_ja) values
('hero.note','Trân trọng kính mời bạn đến chung vui trong ngày hạnh phúc của chúng tôi.','We warmly invite you to celebrate this joyful milestone with us.','私たちの大切な日に、ぜひ一緒にお祝いください。'),
('story.title','Một hành trình, một lời hẹn','One journey, one promise','ひとつの旅、ひとつの約束'),
('story.text','Có những cuộc gặp gỡ làm thay đổi cả một hành trình. Sau những ngày đồng hành, chúng tôi chọn bước tiếp cùng nhau bằng một lời hứa giản dị: luôn là gia đình của nhau.','Some encounters change the course of a lifetime. After walking side by side, we chose to continue this journey together with a simple promise: to always be each other’s family.','人生の道のりを変える出会いがあります。共に歩んできた日々を経て、私たちはこれからも家族として寄り添い続けることを約束し、新しい一歩を踏み出します。'),
('guide.subtitle','Một vài thông tin nhỏ để bạn có thể tận hưởng ngày vui thật thoải mái.','A few details to help you enjoy the celebration comfortably.','当日をゆっくり楽しんでいただくための、ちょっとしたご案内です。'),
('travel.hcm.text','Nếu lưu trú qua đêm, khu vực Bình Thạnh / Bình Lợi Trung sẽ thuận tiện hơn để đến Gold Palace.','If you stay overnight, Bình Thạnh / Bình Lợi Trung is a convenient area for getting to Gold Palace.','宿泊される場合は、Gold Palaceへ移動しやすいBình Thạnh / Bình Lợi Trung周辺が便利です。'),
('travel.rg.text','Nếu ở lại Rạch Giá, khu vực trung tâm thành phố sẽ giúp bạn thuận tiện di chuyển giữa tư gia và địa điểm tiệc.','If you stay in Rạch Giá, the city center is convenient for traveling between the family home and the reception venue.','ラックザーに宿泊される場合は、ご自宅と披露宴会場の間を移動しやすい市中心部が便利です。'),
('rsvp.subtitle','Phản hồi của bạn giúp chúng tôi chuẩn bị chu đáo hơn cho ngày đặc biệt này.','Your response helps us prepare thoughtfully for our special day.','ご出欠をお知らせいただけると、当日の準備に大変助かります。'),
('footer.thanks','Cảm ơn bạn đã trở thành một phần trong câu chuyện của chúng tôi.','Thank you for being part of our story.','私たちの物語の一部になってくださり、ありがとうございます。')
on conflict (key) do nothing;


-- =========================================================
-- Personalized invitation access tracking
-- =========================================================
alter table public.guest_invites
  add column if not exists display_name text,
  add column if not exists companion_name text,
  add column if not exists side text not null default 'friend',
  add column if not exists preferred_language text not null default 'vi',
  add column if not exists sent_at timestamptz,
  add column if not exists opened_at timestamptz,
  add column if not exists last_opened_at timestamptz,
  add column if not exists open_count integer not null default 0;

alter table public.guest_invites
  drop constraint if exists guest_invites_side_check,
  drop constraint if exists guest_invites_preferred_language_check,
  drop constraint if exists guest_invites_display_name_check,
  drop constraint if exists guest_invites_companion_name_check,
  drop constraint if exists guest_invites_open_count_check;

alter table public.guest_invites
  add constraint guest_invites_side_check check (side in ('groom','bride','friend','colleague','family','other')),
  add constraint guest_invites_preferred_language_check check (preferred_language in ('vi','en','ja')),
  add constraint guest_invites_display_name_check check (display_name is null or char_length(display_name) <= 160),
  add constraint guest_invites_companion_name_check check (companion_name is null or char_length(companion_name) <= 160),
  add constraint guest_invites_open_count_check check (open_count >= 0);

drop function if exists public.get_wedding_invite(text);
create function public.get_wedding_invite(p_token text)
returns table (
  id uuid,
  guest_name text,
  display_name text,
  companion_name text,
  phone text,
  event_choice text,
  max_guests integer,
  side text,
  preferred_language text,
  sent_at timestamptz,
  opened_at timestamptz,
  open_count integer
)
language sql
security definer
set search_path = public
stable
as $$
  select gi.id, gi.guest_name, gi.display_name, gi.companion_name, gi.phone,
         gi.event_choice, gi.max_guests, gi.side, gi.preferred_language,
         gi.sent_at, gi.opened_at, gi.open_count
  from public.guest_invites gi
  where gi.token::text = p_token
    and gi.is_active = true
  limit 1;
$$;

revoke all on function public.get_wedding_invite(text) from public;
grant execute on function public.get_wedding_invite(text) to anon;

create or replace function public.mark_wedding_invite_opened(p_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_updated integer;
begin
  update public.guest_invites
     set opened_at = coalesce(opened_at, now()),
         last_opened_at = now(),
         open_count = open_count + 1,
         updated_at = now()
   where token::text = p_token
     and is_active = true;
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

revoke all on function public.mark_wedding_invite_opened(text) from public;
grant execute on function public.mark_wedding_invite_opened(text) to anon;
