create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  guest_name text not null
    check (
      char_length(trim(guest_name)) >= 1
      and char_length(trim(guest_name)) <= 120
    ),
  attendance text not null
    check (attendance in ('yes', 'no', 'maybe')),
  guest_count integer not null default 1
    check (guest_count between 0 and 10),
  message text
    check (message is null or char_length(message) <= 1000),
  event_code text not null default 'general'
    check (char_length(event_code) <= 50),
  created_at timestamptz not null default now(),
  phone text
    check (phone is null or char_length(phone) <= 40),
  event_choice text not null default 'both'
    check (event_choice in ('bride', 'groom', 'both'))
);

alter table public.rsvp enable row level security;

-- Frontend RSVP is intentionally write-only:
-- guests may submit, but cannot read or modify the guest list.
revoke all on table public.rsvp from anon, authenticated;
grant insert on table public.rsvp to anon, authenticated;
grant usage, select on sequence public.rsvp_id_seq to anon, authenticated;

drop policy if exists public_can_submit_rsvp on public.rsvp;

create policy public_can_submit_rsvp
on public.rsvp
for insert
to anon, authenticated
with check (
  char_length(trim(guest_name)) between 1 and 120
  and attendance in ('yes', 'no', 'maybe')
  and guest_count between 0 and 10
  and (phone is null or char_length(phone) <= 40)
  and event_choice in ('bride', 'groom', 'both')
  and (message is null or char_length(message) <= 1000)
);
