create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  attending boolean not null,
  guest_count integer not null default 1 check (guest_count between 0 and 20),
  event_choice text not null check (event_choice in ('bride','groom','both')),
  message text,
  created_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;

-- Khách chỉ được gửi RSVP, không được đọc danh sách của người khác.
create policy "public can submit rsvp"
on public.rsvps
for insert
to anon
with check (true);

-- Không tạo SELECT policy cho anon để giữ riêng tư danh sách khách.
