(() => {
  const cfg = window.WEDDING_CONFIG || {}, status = document.getElementById('albumStatus'), gallery = document.getElementById('gallery'), filters = document.getElementById('albumFilters'), lightbox = document.getElementById('lightbox'), lbImg = document.getElementById('lightboxImage'), lbCaption = document.getElementById('lightboxCaption'), lbCounter = document.getElementById('lightboxCounter');
  if (!cfg.supabaseUrl || !cfg.supabaseAnonKey || !window.supabase) { status.textContent = 'Album chưa được cấu hình.'; return; }
  const db = window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey); let albums = [], images = [], visible = [], currentIndex = 0, activeAlbum = 'all';
  const tr = (key, fallback='') => window.WeddingI18n?.t(key) || fallback || key;
  const albumTitle = (album) => {
    if (!album) return '';
    const key = album.slug === 'pre-wedding' ? 'album.prewedding' : album.slug === 'nha-gai' ? 'album.bride' : album.slug === 'nha-trai' ? 'album.groom' : '';
    return key ? tr(key, album.title) : album.title;
  };
  const publicUrl = path => db.storage.from('wedding-gallery').getPublicUrl(path).data.publicUrl, esc = s => String(s || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const localizedImage = (img) => {
    const lang = window.WeddingI18n?.language || 'vi';
    if (lang === 'en') return {title: img.title_en || img.title, caption: img.caption_en || img.caption, alt: img.alt_text_en || img.alt_text || img.title_en || img.title};
    if (lang === 'ja') return {title: img.title_ja || img.title, caption: img.caption_ja || img.caption, alt: img.alt_text_ja || img.alt_text || img.title_ja || img.title};
    return {title: img.title, caption: img.caption, alt: img.alt_text || img.title};
  };
  function renderFilters(){const all={slug:'all',title:tr('album.all','Tất cả')};filters.innerHTML = [all, ...albums].map(a => `<button class="filter-btn ${activeAlbum===a.slug?'active':''}" data-slug="${a.slug}">${esc(a.slug==='all'?a.title:albumTitle(a))}</button>`).join('');filters.querySelectorAll('button').forEach(btn => btn.onclick = () => { activeAlbum = btn.dataset.slug; renderFilters(); renderGallery(); });}
  function renderGallery(){const albumById = Object.fromEntries(albums.map(a => [a.id,a]));visible = images.filter(img => activeAlbum==='all' || albumById[img.album_id]?.slug===activeAlbum);if (!visible.length){ gallery.innerHTML='<div class="empty">'+esc(tr('album.empty','Album này chưa có ảnh. Hẹn bạn quay lại sớm nhé ♡'))+'</div>'; return; }gallery.innerHTML = visible.map((img,i)=>{const loc=localizedImage(img);return `<article class="photo-card" data-index="${i}"><img loading="lazy" decoding="async" src="${publicUrl(img.image_path)}" alt="${esc(loc.alt || 'Hải Phạm & Mỹ Nguyễn')}"><div class="photo-overlay"><strong>${esc(loc.title || albumTitle(albumById[img.album_id]) || '')}</strong><span>${esc(loc.caption || '')}</span></div></article>`}).join('');gallery.querySelectorAll('.photo-card').forEach(card => card.onclick=()=>openLightbox(Number(card.dataset.index)));}
  function openLightbox(i){ currentIndex=i; const img=visible[i]; if(!img)return; const loc=localizedImage(img); lbImg.src=publicUrl(img.image_path); lbImg.alt=loc.alt||loc.title||'Hải Phạm & Mỹ Nguyễn'; lbCaption.textContent=loc.caption||loc.title||''; if(lbCounter)lbCounter.textContent=`${i+1} / ${visible.length}`; lightbox.showModal(); }function move(delta){ if(!visible.length)return; openLightbox((currentIndex+delta+visible.length)%visible.length); }
  document.getElementById('lightboxClose').onclick=()=>lightbox.close();document.getElementById('lightboxPrev').onclick=()=>move(-1);document.getElementById('lightboxNext').onclick=()=>move(1);lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});document.addEventListener('keydown',e=>{if(!lightbox.open)return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='Escape')lightbox.close()});let touchX=0;lightbox.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});lightbox.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45)move(d>0?-1:1)},{passive:true});
  async function init(){const [a,i] = await Promise.all([db.from('gallery_albums').select('id,title,slug,description,sort_order').order('sort_order'),db.from('gallery_images').select('id,album_id,image_path,title,caption,alt_text,title_en,caption_en,alt_text_en,title_ja,caption_ja,alt_text_ja,width,height,sort_order,created_at').order('sort_order').order('created_at',{ascending:false})]);if(a.error||i.error){status.textContent='Không tải được album.';console.error(a.error||i.error);return;}albums=a.data||[];images=i.data||[];status.textContent=images.length?`${images.length} ${tr('album.moments','khoảnh khắc')}`:'';renderFilters();renderGallery();}init();
  document.addEventListener('wedding:language',()=>{renderFilters();renderGallery();if(images.length)status.textContent=`${images.length} ${tr('album.moments','khoảnh khắc')}`;});
})();