(() => {
  const cfg = window.WEDDING_CONFIG || {}, status = document.getElementById('albumStatus'), gallery = document.getElementById('gallery'), filters = document.getElementById('albumFilters'), lightbox = document.getElementById('lightbox'), lbImg = document.getElementById('lightboxImage'), lbCaption = document.getElementById('lightboxCaption');
  if (!cfg.supabaseUrl || !cfg.supabaseAnonKey || !window.supabase) { status.textContent = 'Album chưa được cấu hình.'; return; }
  const db = window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey); let albums = [], images = [], visible = [], currentIndex = 0, activeAlbum = 'all';
  const publicUrl = path => db.storage.from('wedding-gallery').getPublicUrl(path).data.publicUrl, esc = s => String(s || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function renderFilters(){filters.innerHTML = [{slug:'all',title:'Tất cả'}, ...albums].map(a => `<button class="filter-btn ${activeAlbum===a.slug?'active':''}" data-slug="${a.slug}">${esc(a.title)}</button>`).join('');filters.querySelectorAll('button').forEach(btn => btn.onclick = () => { activeAlbum = btn.dataset.slug; renderFilters(); renderGallery(); });}
  function renderGallery(){const albumById = Object.fromEntries(albums.map(a => [a.id,a]));visible = images.filter(img => activeAlbum==='all' || albumById[img.album_id]?.slug===activeAlbum);if (!visible.length){ gallery.innerHTML='<div class="empty">Album này chưa có ảnh. Hẹn bạn quay lại sớm nhé ♡</div>'; return; }gallery.innerHTML = visible.map((img,i)=>`<article class="photo-card" data-index="${i}"><img loading="lazy" decoding="async" src="${publicUrl(img.image_path)}" alt="${esc(img.alt_text || img.title || 'Ảnh cưới Hải và Mỹ')}"><div class="photo-overlay"><strong>${esc(img.title || albumById[img.album_id]?.title || '')}</strong><span>${esc(img.caption || '')}</span></div></article>`).join('');gallery.querySelectorAll('.photo-card').forEach(card => card.onclick=()=>openLightbox(Number(card.dataset.index)));}
  function openLightbox(i){ currentIndex=i; const img=visible[i]; if(!img)return; lbImg.src=publicUrl(img.image_path); lbImg.alt=img.alt_text||img.title||'Ảnh cưới'; lbCaption.textContent=img.caption||img.title||''; lightbox.showModal(); }function move(delta){ if(!visible.length)return; openLightbox((currentIndex+delta+visible.length)%visible.length); }
  document.getElementById('lightboxClose').onclick=()=>lightbox.close();document.getElementById('lightboxPrev').onclick=()=>move(-1);document.getElementById('lightboxNext').onclick=()=>move(1);lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});document.addEventListener('keydown',e=>{if(!lightbox.open)return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='Escape')lightbox.close()});let touchX=0;lightbox.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});lightbox.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>45)move(d>0?-1:1)},{passive:true});
  async function init(){const [a,i] = await Promise.all([db.from('gallery_albums').select('id,title,slug,description,sort_order').order('sort_order'),db.from('gallery_images').select('id,album_id,image_path,title,caption,alt_text,width,height,sort_order,created_at').order('sort_order').order('created_at',{ascending:false})]);if(a.error||i.error){status.textContent='Không tải được album.';console.error(a.error||i.error);return;}albums=a.data||[];images=i.data||[];status.textContent=images.length?`${images.length} khoảnh khắc`:'';renderFilters();renderGallery();}init();
})();