(() => {
  const A=window.AdminApp,db=A.db,canvas=document.getElementById('editorCanvas'),ctx=canvas.getContext('2d'),file=document.getElementById('fileInput'),ratio=document.getElementById('ratioSelect'),zoom=document.getElementById('zoomRange'),hint=document.getElementById('dropHint'),album=document.getElementById('albumSelect'),status=document.getElementById('uploadStatus');
  function loadBlob(blob,name='image'){return new Promise((ok,no)=>{const img=new Image(),u=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(u);A.sourceImage=img;A.sourceBlob=blob;A.sourceName=name;A.rotation=0;zoom.value='1';hint.classList.add('hidden');draw();ok();};img.onerror=()=>{URL.revokeObjectURL(u);no(new Error('Không đọc được ảnh này. Hãy dùng JPG, PNG hoặc WebP.'));};img.src=u;});}
  A.fileQueue=[];
  async function loadNextQueued(){
    const next=A.fileQueue.shift();
    if(!next){reset();return false;}
    A.editRecord=null;
    try{
      await loadBlob(next,next.name);
      document.getElementById('imageTitle').value=next.name.replace(/\.[^.]+$/,'');
      A.setStatus(status,A.fileQueue.length ? `Đang chỉnh ảnh này. Còn ${A.fileQueue.length} ảnh trong hàng đợi.` : 'Đang chỉnh ảnh đã chọn.','success');
      return true;
    }catch(e){A.setStatus(status,e.message,'error');return loadNextQueued();}
  }
  file.onchange=async()=>{if(!file.files.length)return;A.fileQueue=[...file.files];await loadNextQueued();};
  const stage=document.querySelector('.editor-stage');stage.ondragover=e=>e.preventDefault();stage.ondrop=async e=>{e.preventDefault();A.fileQueue=[...e.dataTransfer.files].filter(x=>x.type.startsWith('image/'));if(A.fileQueue.length)await loadNextQueued();};
  ratio.onchange=draw;zoom.oninput=draw;document.getElementById('rotateLeft').onclick=()=>{A.rotation=(A.rotation-90)%360;draw()};document.getElementById('rotateRight').onclick=()=>{A.rotation=(A.rotation+90)%360;draw()};
  function ratioValue(){if(ratio.value==='free')return null;const [a,b]=ratio.value.split(':').map(Number);return a/b;}
  function draw(){if(!A.sourceImage){ctx.clearRect(0,0,canvas.width,canvas.height);return;}const rotated=Math.abs(A.rotation)%180===90,iw=rotated?A.sourceImage.naturalHeight:A.sourceImage.naturalWidth,ih=rotated?A.sourceImage.naturalWidth:A.sourceImage.naturalHeight,r=ratioValue()||iw/ih,max=1200;let cw,ch;if(r>=1){cw=max;ch=Math.round(max/r)}else{ch=max;cw=Math.round(max*r)}canvas.width=cw;canvas.height=ch;ctx.fillStyle='#eee7e1';ctx.fillRect(0,0,cw,ch);ctx.save();ctx.translate(cw/2,ch/2);ctx.rotate(A.rotation*Math.PI/180);const z=Number(zoom.value),sw=A.sourceImage.naturalWidth,sh=A.sourceImage.naturalHeight,fit=Math.max(cw/(rotated?sh:sw),ch/(rotated?sw:sh))*z;ctx.drawImage(A.sourceImage,-sw*fit/2,-sh*fit/2,sw*fit,sh*fit);ctx.restore();}
  const blob=()=>new Promise(ok=>canvas.toBlob(ok,'image/webp',.82));
  const masterBlob=()=>new Promise(ok=>{
    const img=A.sourceImage,max=2800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));
    const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));
    const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);c.toBlob(ok,'image/webp',.9);
  });
  document.addEventListener('admin:edit',async e=>{const img=e.detail;A.setStatus(status,'Đang tải ảnh gốc...');const {data,error}=await db.storage.from('wedding-originals').download(img.original_path);if(error)return A.setStatus(status,error.message,'error');A.editRecord=img;await loadBlob(data,img.original_path.split('/').pop());album.value=img.album_id;document.getElementById('imageTitle').value=img.title||'';document.getElementById('imageCaption').value=img.caption||'';document.getElementById('imageAlt').value=img.alt_text||'';document.getElementById('imageTitleEn').value=img.title_en||'';document.getElementById('imageCaptionEn').value=img.caption_en||'';document.getElementById('imageAltEn').value=img.alt_text_en||'';document.getElementById('imageTitleJa').value=img.title_ja||'';document.getElementById('imageCaptionJa').value=img.caption_ja||'';document.getElementById('imageAltJa').value=img.alt_text_ja||'';document.getElementById('publishCheck').checked=img.is_published;document.getElementById('cancelEditBtn').classList.remove('hidden');document.querySelector('.upload-panel').scrollIntoView({behavior:'smooth'});A.setStatus(status,'Đang chỉnh sửa ảnh hiện có.','success');});
  document.getElementById('cancelEditBtn').onclick=reset;
  function reset(clearQueue=true){A.editRecord=null;A.sourceImage=null;A.sourceBlob=null;A.sourceName='';if(clearQueue)A.fileQueue=[];file.value='';['imageTitle','imageCaption','imageAlt','imageTitleEn','imageCaptionEn','imageAltEn','imageTitleJa','imageCaptionJa','imageAltJa'].forEach(id=>document.getElementById(id).value='');document.getElementById('cancelEditBtn').classList.add('hidden');hint.classList.remove('hidden');ctx.clearRect(0,0,canvas.width,canvas.height);A.setStatus(status,'');}
  document.getElementById('saveImageBtn').onclick=async()=>{
    if(!A.sourceImage||!A.sourceBlob)return A.setStatus(status,'Hãy chọn ảnh trước.','error');const al=A.albums.find(x=>x.id===album.value);if(!al)return;A.setStatus(status,'Đang xử lý và upload...');const out=await blob();if(!out)return A.setStatus(status,'Không xử lý được ảnh.','error');
    const title=document.getElementById('imageTitle').value.trim(),caption=document.getElementById('imageCaption').value.trim(),alt=document.getElementById('imageAlt').value.trim(),titleEn=document.getElementById('imageTitleEn').value.trim(),captionEn=document.getElementById('imageCaptionEn').value.trim(),altEn=document.getElementById('imageAltEn').value.trim(),titleJa=document.getElementById('imageTitleJa').value.trim(),captionJa=document.getElementById('imageCaptionJa').value.trim(),altJa=document.getElementById('imageAltJa').value.trim(),published=document.getElementById('publishCheck').checked;let id,originalPath,imagePath;
    if(A.editRecord){id=A.editRecord.id;originalPath=A.editRecord.original_path;imagePath=A.editRecord.image_path;}else{id=crypto.randomUUID();originalPath=`${al.slug}/${id}-master.webp`;imagePath=`${al.slug}/${id}.webp`;const master=await masterBlob();if(!master)return A.setStatus(status,'Không tạo được bản master.','error');const u=await db.storage.from('wedding-originals').upload(originalPath,master,{contentType:'image/webp'});if(u.error)return A.setStatus(status,u.error.message,'error');}
    const p=await db.storage.from('wedding-gallery').upload(imagePath,out,{contentType:'image/webp',cacheControl:'3600',upsert:!!A.editRecord});if(p.error)return A.setStatus(status,p.error.message,'error');
    const payload={album_id:al.id,original_path:originalPath,image_path:imagePath,title:title||null,caption:caption||null,alt_text:alt||title||'Ảnh cưới Hải và Mỹ',title_en:titleEn||null,caption_en:captionEn||null,alt_text_en:altEn||titleEn||null,title_ja:titleJa||null,caption_ja:captionJa||null,alt_text_ja:altJa||titleJa||null,width:canvas.width,height:canvas.height,is_published:published,updated_at:new Date().toISOString()};
    const op=A.editRecord?db.from('gallery_images').update(payload).eq('id',id):db.from('gallery_images').insert({...payload,id});const {error}=await op;if(error)return A.setStatus(status,error.message,'error');await A.loadData();if(A.fileQueue.length){reset(false);await loadNextQueued();}else{reset();A.setStatus(status,'Đã lưu ảnh thành công.','success');}
  };
})();